# Generated by Django 5.2.7 on 2025-11-04 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='domain',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
